/* Generated By:JavaCC: Do not edit this line. RDefaultVisitor.java Version 6.1_2 */
package com.garcel.parser.r.visitor;

import com.garcel.parser.r.autogen.*;
import com.garcel.parser.r.node.*;

public class RDefaultVisitor implements RVisitor {
  public void defaultVisit(RNode node, Object data){
    node.childrenAccept(this, data);
  }
  public void visit(RNode node, Object data){
    defaultVisit(node, data);
  }
  public void visit(Program node, Object data){
    defaultVisit(node, data);
  }
  public void visit(Expression node, Object data){
    defaultVisit(node, data);
  }
  public void visit(Condition node, Object data){
    defaultVisit(node, data);
  }
  public void visit(ExpressionList node, Object data){
    defaultVisit(node, data);
  }
  public void visit(SubList node, Object data){
    defaultVisit(node, data);
  }
  public void visit(Sub node, Object data){
    defaultVisit(node, data);
  }
  public void visit(FormList node, Object data){
    defaultVisit(node, data);
  }
  public void visit(Arguments node, Object data){
    defaultVisit(node, data);
  }
  public void visit(Assignment node, Object data){
    defaultVisit(node, data);
  }
  public void visit(Block node, Object data){
    defaultVisit(node, data);
  }
  public void visit(Constant node, Object data){
    defaultVisit(node, data);
  }
  public void visit(For node, Object data){
    defaultVisit(node, data);
  }
  public void visit(Function node, Object data){
    defaultVisit(node, data);
  }
  public void visit(Help node, Object data){
    defaultVisit(node, data);
  }
  public void visit(Identifier node, Object data){
    defaultVisit(node, data);
  }
  public void visit(If node, Object data){
    defaultVisit(node, data);
  }
  public void visit(Repeat node, Object data){
    defaultVisit(node, data);
  }
  public void visit(While node, Object data){
    defaultVisit(node, data);
  }
}
/* JavaCC - OriginalChecksum=110ba3dc198f6f6e89b4b5d25955c967 (do not edit this line) */
