# All files in the distribution of BLOAT (Bytecode Level Optimization and
# Analysis tool for Java(tm)) are Copyright 1997-2001 by the Purdue
# Research Foundation of Purdue University.  All rights reserved.
#
# Redistribution and use in source and binary forms are permitted
# provided that this entire copyright notice is duplicated in all such
# copies, and that any documentation, announcements, and other
# materials related to such distribution and use acknowledge that the
# software was developed at Purdue University, West Lafayette, IN by
# Antony Hosking, David Whitlock, and Nathaniel Nystrom.  No charge
# may be made for copies, derivations, or distributions of this
# material without the express written consent of the copyright
# holder.  Neither the name of the University nor the name of the
# author may be used to endorse or promote products derived from this
# material without specific prior written permission.  THIS SOFTWARE
# IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR IMPLIED WARRANTIES,
# INCLUDING, WITHOUT LIMITATION, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR ANY PARTICULAR PURPOSE.
#
# Java is a trademark of Sun Microsystems, Inc.

CLASS = \
	AddressStoreStmt.class\
	ArithExpr.class\
	ArrayLengthExpr.class\
	ArrayRefExpr.class\
	AscendVisitor.class\
	Assign.class\
	CallExpr.class\
	CallMethodExpr.class\
	CallStaticExpr.class\
	CastExpr.class\
	CatchExpr.class\
	CheckExpr.class\
	CondExpr.class\
	ConstantExpr.class\
	DescendVisitor.class\
	DefExpr.class\
	Expr.class\
	ExprStmt.class\
	FieldExpr.class\
	GotoStmt.class\
	IfCmpStmt.class\
	IfStmt.class\
	IfZeroStmt.class\
	InitStmt.class\
	InstanceOfExpr.class\
	JsrStmt.class\
	JumpStmt.class\
	LabelStmt.class\
	LeafExpr.class\
	LEGatherer.class\
	LocalExpr.class\
	MemExpr.class\
	MemRefExpr.class\
	MonitorStmt.class\
	NegExpr.class\
	NewArrayExpr.class\
	NewExpr.class\
	NewMultiArrayExpr.class\
	Node.class\
	OperandStack.class\
	PhiCatchStmt.class\
	PhiJoinStmt.class\
	PhiStmt.class\
	PrintVisitor.class\
	RCExpr.class\
	ReplaceVisitor.class\
	RetStmt.class\
	ReturnAddressExpr.class\
	ReturnExprStmt.class\
	ReturnStmt.class\
	SCStmt.class\
	SRStmt.class\
	ShiftExpr.class\
	StackExpr.class\
	StackManipStmt.class\
	StaticFieldExpr.class\
	StackOptimizer.class\
	Stmt.class\
	StoreExpr.class\
	SwitchStmt.class\
	Swizzler.class\
	ThrowStmt.class\
	Tree.class\
	TreeVisitor.class\
	Type0Visitor.class\
	Type1Visitor.class\
	UCExpr.class\
	VarExpr.class\
	ZeroCheckExpr.class

include ../class.mk






